spring:
  application:
    name: utility

  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
        # 连接池最大连接数，使用负数表示没有限制，默认为-1
        max-active: 8
        # 连接池最大阻塞等待时间，使用负数表示没有限制，默认为-1
        max-wait: -1
        # 连接池最大空闲连接数量，默认为8
        max-idle: 8
        # 连接池最小连接数，默认0
        min-idle: 1
    database: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

